// Copyright (c) 2026 Oleksandr Melnychenko. All rights reserved.
// SPDX-License-Identifier: MIT

//! Aura Channel encryption — broadcast E2E for channel posts.
//!
//! ## Threat model
//! - One symmetric AES-256-GCM-SIV channel key per epoch (32 bytes), generated by
//!   the channel admin client-side.
//! - Admin wraps the key for each subscriber device using hybrid X25519 ECDH +
//!   ML-KEM-768 and ships the wrapped blobs to the channels server, which only
//!   stores opaque bytes.
//! - Each subscriber unwraps with their device X25519 private key and ML-KEM-768
//!   secret key to obtain the raw channel key, which is cached locally (encrypted
//!   at rest).
//! - To post: random 12-byte nonce, AES-256-GCM-SIV encrypt with the channel key,
//!   then sign `(channel_id || generation_be8 || ciphertext)` with the sender's
//!   Ed25519 identity key.
//! - To read: verify Ed25519 signature against the claimed sender public key,
//!   then AES-256-GCM-SIV decrypt with the cached channel key.
//!
//! ## Wire format decoupling
//! All functions in this module operate on raw byte arrays. The transport
//! envelope (`ProtoEncryptedChannelMessage` in the gateway proto) is assembled
//! by the calling layer (iOS Swift via FFI, or the Rust gateway crate). APP core
//! intentionally has no `prost` dependency on the channels proto schema so it
//! can be reused across transports.
//!
//! ## Wrapped key blob layout
//! ```text
//! offset  size   field
//! 0       32     ephemeral X25519 public key
//! 32      1088   ML-KEM-768 ciphertext
//! 1120    12     AES-GCM-SIV nonce
//! 1132    48     AES-GCM-SIV ciphertext (32-byte channel key + 16-byte tag)
//! ```
//! Total: [`CHANNEL_KEY_BLOB_BYTES`] = 1180 bytes.

use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use hkdf::Hkdf;
use rand_core::{OsRng, RngCore};
use sha2::Sha256;
use x25519_dalek::{PublicKey as X25519Public, StaticSecret as X25519Secret};
use zeroize::Zeroizing;

use crate::core::constants::{
    AES_GCM_NONCE_BYTES, AES_GCM_TAG_BYTES, AES_KEY_BYTES, ED25519_PUBLIC_KEY_BYTES,
    ED25519_SIGNATURE_BYTES, KYBER_CIPHERTEXT_BYTES, KYBER_PUBLIC_KEY_BYTES,
    KYBER_SHARED_SECRET_BYTES, MAX_ENVELOPE_MESSAGE_SIZE, X25519_PRIVATE_KEY_BYTES,
    X25519_PUBLIC_KEY_BYTES,
};
use crate::core::errors::ProtocolError;
use crate::crypto::{AesGcm, KyberInterop, SecureMemoryHandle};

/// Channel key identifier — 16 bytes (UUID v4 layout).
pub const CHANNEL_KEY_ID_BYTES: usize = 16;
/// Channel identifier — 16 bytes (UUID v4 layout).
pub const CHANNEL_ID_BYTES: usize = 16;
/// Ed25519 secret seed length expected by [`encrypt_message`].
pub const CHANNEL_ED25519_SECRET_BYTES: usize = 32;

const HKDF_INFO_WRAP: &[u8] = b"Aura-Channel-KeyWrap-Hybrid-X25519-MLKEM768-v1";
const AAD_TAG_MESSAGE: &[u8] = b"aura-channel-msg-v1";
const AAD_TAG_WRAP: &[u8] = b"aura-channel-wrap-hybrid-v1";

/// Total length of a wrapped channel-key blob produced by [`wrap_key_for_device`].
pub const CHANNEL_KEY_BLOB_BYTES: usize = X25519_PUBLIC_KEY_BYTES
    + KYBER_CIPHERTEXT_BYTES
    + AES_GCM_NONCE_BYTES
    + AES_KEY_BYTES
    + AES_GCM_TAG_BYTES;

/// A freshly generated channel key with its UUID identifier.
pub struct ChannelKeyMaterial {
    pub key_id: [u8; CHANNEL_KEY_ID_BYTES],
    pub key: Zeroizing<[u8; AES_KEY_BYTES]>,
}

/// Output of [`encrypt_message`] — caller assembles the wire envelope from these
/// fields (e.g. into `ProtoEncryptedChannelMessage`).
pub struct ChannelEncryptedFields {
    pub channel_key_id: [u8; CHANNEL_KEY_ID_BYTES],
    pub generation: u64,
    pub nonce: [u8; AES_GCM_NONCE_BYTES],
    pub ciphertext: Vec<u8>,
    pub sender_signature: [u8; ED25519_SIGNATURE_BYTES],
}

/// Output of [`decrypt_message`].
pub struct ChannelDecryptedMessage {
    pub plaintext: Vec<u8>,
    pub channel_key_id: [u8; CHANNEL_KEY_ID_BYTES],
    pub generation: u64,
}

/// Generate a fresh symmetric channel key + UUID v4 identifier.
///
/// Both the identifier and the key bytes are sourced from the operating system's
/// CSPRNG. The returned key is wrapped in [`Zeroizing`] so it is wiped on drop.
pub fn generate_channel_key() -> Result<ChannelKeyMaterial, ProtocolError> {
    let mut key_id = [0u8; CHANNEL_KEY_ID_BYTES];
    let mut key = Zeroizing::new([0u8; AES_KEY_BYTES]);
    OsRng
        .try_fill_bytes(&mut key_id)
        .map_err(|_| ProtocolError::generic("Channel key generation: OS RNG failed for key id"))?;
    OsRng
        .try_fill_bytes(&mut *key)
        .map_err(|_| ProtocolError::generic("Channel key generation: OS RNG failed for key"))?;
    // Stamp UUID v4 variant + version bits so the identifier is a valid RFC 4122 UUID.
    key_id[6] = (key_id[6] & 0x0f) | 0x40;
    key_id[8] = (key_id[8] & 0x3f) | 0x80;
    Ok(ChannelKeyMaterial { key_id, key })
}

/// Wrap a 32-byte channel key for a single subscriber device.
///
/// Uses hybrid X25519 ECDH + ML-KEM-768 and returns a
/// [`CHANNEL_KEY_BLOB_BYTES`]-sized opaque blob suitable for upload via the
/// channels `DistributeKey` RPC.
pub fn wrap_key_for_device(
    channel_key: &[u8; AES_KEY_BYTES],
    device_x25519_public: &[u8; X25519_PUBLIC_KEY_BYTES],
    device_kyber_public: &[u8; KYBER_PUBLIC_KEY_BYTES],
) -> Result<Vec<u8>, ProtocolError> {
    KyberInterop::validate_public_key(device_kyber_public)?;

    let ephemeral_secret = X25519Secret::random_from_rng(OsRng);
    let ephemeral_public = X25519Public::from(&ephemeral_secret);

    let device_public = X25519Public::from(*device_x25519_public);
    let shared = ephemeral_secret.diffie_hellman(&device_public);
    if !shared.was_contributory() {
        return Err(ProtocolError::generic(
            "Channel key wrap: peer X25519 public key was non-contributory",
        ));
    }

    let (kyber_ciphertext, kyber_shared_handle) = KyberInterop::encapsulate(device_kyber_public)?;
    let kyber_shared = kyber_shared_handle.read_zeroizing(KYBER_SHARED_SECRET_BYTES)?;

    let mut wrapping_key = derive_wrap_key(
        ephemeral_public.as_bytes(),
        device_x25519_public,
        &kyber_ciphertext,
        shared.as_bytes(),
        &kyber_shared,
    )?;

    let mut nonce = [0u8; AES_GCM_NONCE_BYTES];
    OsRng
        .try_fill_bytes(&mut nonce)
        .map_err(|_| ProtocolError::generic("Channel key wrap: OS RNG failed for nonce"))?;

    let aad = build_wrap_aad(
        ephemeral_public.as_bytes(),
        device_x25519_public,
        &kyber_ciphertext,
    );
    let ciphertext = AesGcm::encrypt(&*wrapping_key, &nonce, channel_key.as_slice(), &aad)?;
    debug_assert_eq!(ciphertext.len(), AES_KEY_BYTES + AES_GCM_TAG_BYTES);

    // Best-effort wipe of the derived wrapping key (drop will also zeroize).
    wrapping_key.iter_mut().for_each(|b| *b = 0);

    let mut blob = Vec::with_capacity(CHANNEL_KEY_BLOB_BYTES);
    blob.extend_from_slice(ephemeral_public.as_bytes());
    blob.extend_from_slice(&kyber_ciphertext);
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    debug_assert_eq!(blob.len(), CHANNEL_KEY_BLOB_BYTES);
    Ok(blob)
}

/// Unwrap a [`CHANNEL_KEY_BLOB_BYTES`]-sized blob using the device's X25519
/// private key and ML-KEM-768 secret key, returning the raw 32-byte channel key.
pub fn unwrap_key_blob(
    blob: &[u8],
    device_x25519_secret: &[u8; X25519_PRIVATE_KEY_BYTES],
    device_kyber_secret: &SecureMemoryHandle,
) -> Result<Zeroizing<[u8; AES_KEY_BYTES]>, ProtocolError> {
    if blob.len() != CHANNEL_KEY_BLOB_BYTES {
        return Err(ProtocolError::invalid_input(format!(
            "Channel key blob must be {CHANNEL_KEY_BLOB_BYTES} bytes, got {}",
            blob.len()
        )));
    }

    let mut ephemeral_pub_bytes = [0u8; X25519_PUBLIC_KEY_BYTES];
    ephemeral_pub_bytes.copy_from_slice(&blob[..X25519_PUBLIC_KEY_BYTES]);
    let ephemeral_public = X25519Public::from(ephemeral_pub_bytes);

    let kyber_offset = X25519_PUBLIC_KEY_BYTES;
    let kyber_end = kyber_offset + KYBER_CIPHERTEXT_BYTES;
    let kyber_ciphertext = &blob[kyber_offset..kyber_end];
    KyberInterop::validate_ciphertext(kyber_ciphertext)?;

    let nonce_offset = kyber_end;
    let nonce_end = nonce_offset + AES_GCM_NONCE_BYTES;
    let mut nonce = [0u8; AES_GCM_NONCE_BYTES];
    nonce.copy_from_slice(&blob[nonce_offset..nonce_end]);
    let ciphertext = &blob[nonce_end..];

    let device_secret = X25519Secret::from(*device_x25519_secret);
    let shared = device_secret.diffie_hellman(&ephemeral_public);
    if !shared.was_contributory() {
        return Err(ProtocolError::generic(
            "Channel key unwrap: peer X25519 public key was non-contributory",
        ));
    }

    let kyber_shared_handle = KyberInterop::decapsulate(kyber_ciphertext, device_kyber_secret)?;
    let kyber_shared = kyber_shared_handle.read_zeroizing(KYBER_SHARED_SECRET_BYTES)?;

    let device_public = X25519Public::from(&device_secret);
    let mut wrapping_key = derive_wrap_key(
        ephemeral_public.as_bytes(),
        device_public.as_bytes(),
        kyber_ciphertext,
        shared.as_bytes(),
        &kyber_shared,
    )?;

    let aad = build_wrap_aad(
        ephemeral_public.as_bytes(),
        device_public.as_bytes(),
        kyber_ciphertext,
    );
    let plaintext = AesGcm::decrypt(&*wrapping_key, &nonce, ciphertext, &aad)?;

    wrapping_key.iter_mut().for_each(|b| *b = 0);

    if plaintext.len() != AES_KEY_BYTES {
        return Err(ProtocolError::invalid_input(format!(
            "Unwrapped channel key must be {AES_KEY_BYTES} bytes, got {}",
            plaintext.len()
        )));
    }
    let mut out = Zeroizing::new([0u8; AES_KEY_BYTES]);
    out.copy_from_slice(&plaintext);
    Ok(out)
}

/// Encrypt a channel message. The returned [`ChannelEncryptedFields`] are ready
/// to be assembled into the wire envelope by the caller.
pub fn encrypt_message(
    plaintext: &[u8],
    channel_key: &[u8; AES_KEY_BYTES],
    channel_id: &[u8; CHANNEL_ID_BYTES],
    channel_key_id: &[u8; CHANNEL_KEY_ID_BYTES],
    generation: u64,
    sender_ed25519_secret: &[u8; CHANNEL_ED25519_SECRET_BYTES],
) -> Result<ChannelEncryptedFields, ProtocolError> {
    if plaintext.len() > MAX_ENVELOPE_MESSAGE_SIZE {
        return Err(ProtocolError::invalid_input(format!(
            "Channel message plaintext exceeds {MAX_ENVELOPE_MESSAGE_SIZE} bytes"
        )));
    }

    let mut nonce = [0u8; AES_GCM_NONCE_BYTES];
    OsRng
        .try_fill_bytes(&mut nonce)
        .map_err(|_| ProtocolError::generic("Channel encrypt: OS RNG failed for nonce"))?;

    let aad = build_message_aad(channel_id, channel_key_id, generation);
    let ciphertext = AesGcm::encrypt(channel_key, &nonce, plaintext, &aad)?;

    let signing_key = SigningKey::from_bytes(sender_ed25519_secret);
    let signed_payload = build_signed_payload(channel_id, generation, &ciphertext);
    let signature = signing_key.sign(&signed_payload);

    Ok(ChannelEncryptedFields {
        channel_key_id: *channel_key_id,
        generation,
        nonce,
        ciphertext,
        sender_signature: signature.to_bytes(),
    })
}

/// Decrypt a channel message previously produced by [`encrypt_message`].
///
/// Verifies the Ed25519 signature against `sender_ed25519_public`, then performs
/// AES-GCM-SIV decryption.
pub fn decrypt_message(
    fields: &ChannelEncryptedFields,
    channel_key: &[u8; AES_KEY_BYTES],
    channel_id: &[u8; CHANNEL_ID_BYTES],
    sender_ed25519_public: &[u8; ED25519_PUBLIC_KEY_BYTES],
) -> Result<ChannelDecryptedMessage, ProtocolError> {
    if fields.ciphertext.len() < AES_GCM_TAG_BYTES {
        return Err(ProtocolError::invalid_input(format!(
            "Channel ciphertext too small ({}) for AES-GCM tag ({} bytes minimum)",
            fields.ciphertext.len(),
            AES_GCM_TAG_BYTES
        )));
    }
    if fields.ciphertext.len() > MAX_ENVELOPE_MESSAGE_SIZE + AES_GCM_TAG_BYTES {
        return Err(ProtocolError::invalid_input(format!(
            "Channel ciphertext exceeds {} bytes",
            MAX_ENVELOPE_MESSAGE_SIZE + AES_GCM_TAG_BYTES
        )));
    }

    let verifying_key = VerifyingKey::from_bytes(sender_ed25519_public)
        .map_err(|_| ProtocolError::invalid_input("Invalid Ed25519 verifying key"))?;
    let signature = Signature::from_bytes(&fields.sender_signature);
    let signed_payload = build_signed_payload(channel_id, fields.generation, &fields.ciphertext);
    verifying_key
        .verify_strict(&signed_payload, &signature)
        .map_err(|_| {
            ProtocolError::generic("Channel message Ed25519 signature verification failed")
        })?;

    let aad = build_message_aad(channel_id, &fields.channel_key_id, fields.generation);
    let plaintext = AesGcm::decrypt(channel_key, &fields.nonce, &fields.ciphertext, &aad)?;

    Ok(ChannelDecryptedMessage {
        plaintext,
        channel_key_id: fields.channel_key_id,
        generation: fields.generation,
    })
}

fn derive_wrap_key(
    ephemeral_public: &[u8; X25519_PUBLIC_KEY_BYTES],
    device_public: &[u8; X25519_PUBLIC_KEY_BYTES],
    kyber_ciphertext: &[u8],
    x25519_shared_secret: &[u8],
    kyber_shared_secret: &[u8],
) -> Result<Zeroizing<[u8; AES_KEY_BYTES]>, ProtocolError> {
    let mut salt = Vec::with_capacity(
        AAD_TAG_WRAP.len() + 2 * X25519_PUBLIC_KEY_BYTES + KYBER_CIPHERTEXT_BYTES,
    );
    salt.extend_from_slice(AAD_TAG_WRAP);
    salt.extend_from_slice(ephemeral_public);
    salt.extend_from_slice(device_public);
    salt.extend_from_slice(kyber_ciphertext);

    let mut ikm = Zeroizing::new(Vec::with_capacity(
        x25519_shared_secret.len() + kyber_shared_secret.len(),
    ));
    ikm.extend_from_slice(x25519_shared_secret);
    ikm.extend_from_slice(kyber_shared_secret);

    let hkdf = Hkdf::<Sha256>::new(Some(&salt), &ikm);
    let mut wrapping_key = Zeroizing::new([0u8; AES_KEY_BYTES]);
    hkdf.expand(HKDF_INFO_WRAP, &mut *wrapping_key)
        .map_err(|_| ProtocolError::generic("Channel key wrap: HKDF expand failed"))?;
    Ok(wrapping_key)
}

fn build_message_aad(
    channel_id: &[u8; CHANNEL_ID_BYTES],
    channel_key_id: &[u8; CHANNEL_KEY_ID_BYTES],
    generation: u64,
) -> Vec<u8> {
    let mut aad =
        Vec::with_capacity(AAD_TAG_MESSAGE.len() + CHANNEL_ID_BYTES + CHANNEL_KEY_ID_BYTES + 8);
    aad.extend_from_slice(AAD_TAG_MESSAGE);
    aad.extend_from_slice(channel_id);
    aad.extend_from_slice(channel_key_id);
    aad.extend_from_slice(&generation.to_be_bytes());
    aad
}

fn build_wrap_aad(
    ephemeral_public: &[u8; X25519_PUBLIC_KEY_BYTES],
    device_x25519_public: &[u8; X25519_PUBLIC_KEY_BYTES],
    kyber_ciphertext: &[u8],
) -> Vec<u8> {
    let mut aad = Vec::with_capacity(
        AAD_TAG_WRAP.len() + (2 * X25519_PUBLIC_KEY_BYTES) + kyber_ciphertext.len(),
    );
    aad.extend_from_slice(AAD_TAG_WRAP);
    aad.extend_from_slice(ephemeral_public);
    aad.extend_from_slice(device_x25519_public);
    aad.extend_from_slice(kyber_ciphertext);
    aad
}

fn build_signed_payload(
    channel_id: &[u8; CHANNEL_ID_BYTES],
    generation: u64,
    ciphertext: &[u8],
) -> Vec<u8> {
    let mut buf = Vec::with_capacity(CHANNEL_ID_BYTES + 8 + ciphertext.len());
    buf.extend_from_slice(channel_id);
    buf.extend_from_slice(&generation.to_be_bytes());
    buf.extend_from_slice(ciphertext);
    buf
}

#[cfg(test)]
mod tests {
    use super::*;
    use curve25519_dalek::{
        constants::ED25519_BASEPOINT_POINT,
        edwards::{CompressedEdwardsY, EdwardsPoint},
        scalar::Scalar,
        traits::IsIdentity,
    };
    use ed25519_dalek::{SigningKey, Verifier};
    use sha2::{Digest, Sha512};
    use std::ops::Neg;

    const WEAK_ED25519_PUBLIC: [u8; ED25519_PUBLIC_KEY_BYTES] = [
        236, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 127,
    ];

    fn fixture_channel_key() -> [u8; AES_KEY_BYTES] {
        [0xAB; AES_KEY_BYTES]
    }

    fn fixture_channel_id() -> [u8; CHANNEL_ID_BYTES] {
        [0x11; CHANNEL_ID_BYTES]
    }

    fn fixture_channel_key_id() -> [u8; CHANNEL_KEY_ID_BYTES] {
        [0x22; CHANNEL_KEY_ID_BYTES]
    }

    fn fixture_signing_key() -> SigningKey {
        SigningKey::from_bytes(&[0x33; CHANNEL_ED25519_SECRET_BYTES])
    }

    fn fixture_device_x25519() -> (
        [u8; X25519_PRIVATE_KEY_BYTES],
        [u8; X25519_PUBLIC_KEY_BYTES],
    ) {
        let secret = X25519Secret::random_from_rng(OsRng);
        let public = X25519Public::from(&secret);
        (secret.to_bytes(), public.to_bytes())
    }

    fn fixture_device_hybrid() -> (
        [u8; X25519_PRIVATE_KEY_BYTES],
        [u8; X25519_PUBLIC_KEY_BYTES],
        SecureMemoryHandle,
        [u8; KYBER_PUBLIC_KEY_BYTES],
    ) {
        let (x25519_secret, x25519_public) = fixture_device_x25519();
        let (kyber_secret, kyber_public) = KyberInterop::generate_keypair().expect("kyber keypair");
        let kyber_public = kyber_public
            .try_into()
            .expect("kyber public key has expected length");
        (x25519_secret, x25519_public, kyber_secret, kyber_public)
    }

    fn weak_key_forgery_for_message(message: &[u8]) -> [u8; ED25519_SIGNATURE_BYTES] {
        let weak_pub = CompressedEdwardsY(WEAK_ED25519_PUBLIC)
            .decompress()
            .expect("weak public key decompresses");
        for counter in 1u64..10_000 {
            let mut seed = [0u8; 32];
            seed[..8].copy_from_slice(&counter.to_le_bytes());
            let s = Scalar::from_bytes_mod_order(seed);
            if s == Scalar::ZERO {
                continue;
            }
            let r = s * ED25519_BASEPOINT_POINT + weak_pub.neg();
            if (weak_pub.neg() + ed25519_challenge(message, &weak_pub, &r) * weak_pub).is_identity()
            {
                let mut sig = [0u8; ED25519_SIGNATURE_BYTES];
                sig[..32].copy_from_slice(r.compress().as_bytes());
                sig[32..].copy_from_slice(s.as_bytes());
                return sig;
            }
        }
        panic!("failed to construct weak-key forgery for test payload");
    }

    fn ed25519_challenge(message: &[u8], public_key: &EdwardsPoint, r: &EdwardsPoint) -> Scalar {
        let mut h = Sha512::new();
        h.update(r.compress().as_bytes());
        h.update(public_key.compress().as_bytes());
        h.update(message);
        let mut wide = [0u8; 64];
        wide.copy_from_slice(&h.finalize());
        Scalar::from_bytes_mod_order_wide(&wide)
    }

    #[test]
    fn generate_channel_key_yields_uuid_v4_bits() {
        let material = generate_channel_key().expect("generate key");
        // Version nibble == 4 (UUID v4).
        assert_eq!(material.key_id[6] & 0xF0, 0x40);
        // Variant bits == 10xx.
        assert_eq!(material.key_id[8] & 0xC0, 0x80);
        assert_eq!(material.key.len(), AES_KEY_BYTES);
    }

    #[test]
    fn generate_channel_key_is_unique_across_calls() {
        let a = generate_channel_key().expect("a");
        let b = generate_channel_key().expect("b");
        assert_ne!(a.key_id, b.key_id);
        assert_ne!(*a.key, *b.key);
    }

    #[test]
    fn encrypt_decrypt_roundtrip() {
        let signing = fixture_signing_key();
        let plaintext = b"hello world".to_vec();
        let fields = encrypt_message(
            &plaintext,
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            7,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        let decoded = decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .expect("decrypt");

        assert_eq!(decoded.plaintext, plaintext);
        assert_eq!(decoded.channel_key_id, fixture_channel_key_id());
        assert_eq!(decoded.generation, 7);
    }

    #[test]
    fn encrypt_uses_fresh_nonce_each_call() {
        let signing = fixture_signing_key();
        let a = encrypt_message(
            b"same",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            1,
            &signing.to_bytes(),
        )
        .expect("a");
        let b = encrypt_message(
            b"same",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            1,
            &signing.to_bytes(),
        )
        .expect("b");
        assert_ne!(a.nonce, b.nonce);
        assert_ne!(a.ciphertext, b.ciphertext);
    }

    #[test]
    fn decrypt_rejects_wrong_channel_key() {
        let signing = fixture_signing_key();
        let fields = encrypt_message(
            b"secret",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        let wrong_key = [0xCD; AES_KEY_BYTES];
        assert!(decrypt_message(
            &fields,
            &wrong_key,
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_tampered_ciphertext() {
        let signing = fixture_signing_key();
        let mut fields = encrypt_message(
            b"secret",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        fields.ciphertext[0] ^= 0xFF;
        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_tampered_signature() {
        let signing = fixture_signing_key();
        let mut fields = encrypt_message(
            b"secret",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        fields.sender_signature[0] ^= 0xFF;
        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_wrong_sender_public_key() {
        let signing = fixture_signing_key();
        let other = SigningKey::from_bytes(&[0x99; CHANNEL_ED25519_SECRET_BYTES]);
        let fields = encrypt_message(
            b"secret",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            other.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_weak_sender_public_key_forgery() {
        let signing = fixture_signing_key();
        let fields = encrypt_message(
            b"weak-key forgery",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            17,
            &signing.to_bytes(),
        )
        .expect("encrypt");
        let signed_payload =
            build_signed_payload(&fixture_channel_id(), fields.generation, &fields.ciphertext);
        let signature = weak_key_forgery_for_message(&signed_payload);
        let weak_key = VerifyingKey::from_bytes(&WEAK_ED25519_PUBLIC).expect("weak key parses");
        let weak_signature = Signature::from_bytes(&signature);

        assert!(
            weak_key.verify(&signed_payload, &weak_signature).is_ok(),
            "non-strict verification accepts this weak-key forgery"
        );
        assert!(
            weak_key
                .verify_strict(&signed_payload, &weak_signature)
                .is_err(),
            "strict verification rejects weak public keys"
        );

        let forged_fields = ChannelEncryptedFields {
            sender_signature: signature,
            ..fields
        };
        assert!(decrypt_message(
            &forged_fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            &WEAK_ED25519_PUBLIC,
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_wrong_channel_id() {
        let signing = fixture_signing_key();
        let fields = encrypt_message(
            b"secret",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        let wrong_channel = [0x99; CHANNEL_ID_BYTES];
        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &wrong_channel,
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn wrap_unwrap_roundtrip() {
        let (secret, public, kyber_secret, kyber_public) = fixture_device_hybrid();
        let channel_key = fixture_channel_key();

        let blob = wrap_key_for_device(&channel_key, &public, &kyber_public).expect("wrap");
        assert_eq!(blob.len(), CHANNEL_KEY_BLOB_BYTES);

        let unwrapped = unwrap_key_blob(&blob, &secret, &kyber_secret).expect("unwrap");
        assert_eq!(*unwrapped, channel_key);
    }

    #[test]
    fn unwrap_rejects_wrong_device_secret() {
        let (_, public, _, kyber_public) = fixture_device_hybrid();
        let (other_secret, _, other_kyber_secret, _) = fixture_device_hybrid();
        let channel_key = fixture_channel_key();

        let blob = wrap_key_for_device(&channel_key, &public, &kyber_public).expect("wrap");
        assert!(unwrap_key_blob(&blob, &other_secret, &other_kyber_secret).is_err());
    }

    #[test]
    fn unwrap_rejects_truncated_blob() {
        let (secret, _, kyber_secret, _) = fixture_device_hybrid();
        assert!(
            unwrap_key_blob(&[0u8; CHANNEL_KEY_BLOB_BYTES - 1], &secret, &kyber_secret).is_err()
        );
    }

    #[test]
    fn unwrap_rejects_oversized_blob() {
        let (secret, _, kyber_secret, _) = fixture_device_hybrid();
        assert!(
            unwrap_key_blob(&[0u8; CHANNEL_KEY_BLOB_BYTES + 1], &secret, &kyber_secret).is_err()
        );
    }

    #[test]
    fn unwrap_rejects_tampered_blob() {
        let (secret, public, kyber_secret, kyber_public) = fixture_device_hybrid();
        let mut blob =
            wrap_key_for_device(&fixture_channel_key(), &public, &kyber_public).expect("wrap");
        let tag_offset = blob.len() - 1;
        blob[tag_offset] ^= 0xFF;
        assert!(unwrap_key_blob(&blob, &secret, &kyber_secret).is_err());
    }

    #[test]
    fn wrap_each_call_uses_fresh_ephemeral() {
        let (_, public, _, kyber_public) = fixture_device_hybrid();
        let channel_key = fixture_channel_key();
        let a = wrap_key_for_device(&channel_key, &public, &kyber_public).expect("a");
        let b = wrap_key_for_device(&channel_key, &public, &kyber_public).expect("b");
        assert_ne!(a, b, "wrap must be non-deterministic");
    }

    #[test]
    fn encrypt_empty_plaintext_roundtrips() {
        let signing = fixture_signing_key();
        let fields = encrypt_message(
            b"",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt empty");
        // Even with empty plaintext we still produce a 16-byte AES-GCM tag.
        assert_eq!(fields.ciphertext.len(), AES_GCM_TAG_BYTES);

        let decoded = decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .expect("decrypt empty");
        assert!(decoded.plaintext.is_empty());
    }

    #[test]
    fn encrypt_large_plaintext_roundtrips() {
        let signing = fixture_signing_key();
        let plaintext = vec![0xAB; 256 * 1024];
        let fields = encrypt_message(
            &plaintext,
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            42,
            &signing.to_bytes(),
        )
        .expect("encrypt large");
        assert_eq!(fields.ciphertext.len(), plaintext.len() + AES_GCM_TAG_BYTES);

        let decoded = decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .expect("decrypt large");
        assert_eq!(decoded.plaintext, plaintext);
    }

    #[test]
    fn encrypt_rejects_oversized_plaintext() {
        let signing = fixture_signing_key();
        let plaintext = vec![0u8; MAX_ENVELOPE_MESSAGE_SIZE + 1];
        assert!(encrypt_message(
            &plaintext,
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_swapped_key_id_in_fields() {
        // AAD binds channel_key_id; tampering with the announced key_id (e.g. by a
        // gateway operator who controls one but not the other) must fail decryption.
        let signing = fixture_signing_key();
        let mut fields = encrypt_message(
            b"hello",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            5,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        fields.channel_key_id[0] ^= 0xFF;
        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn decrypt_rejects_swapped_generation_in_fields() {
        // AAD + signature both bind generation; bumping it must fail.
        let signing = fixture_signing_key();
        let mut fields = encrypt_message(
            b"hello",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            5,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        fields.generation = 6;
        assert!(decrypt_message(
            &fields,
            &fixture_channel_key(),
            &fixture_channel_id(),
            signing.verifying_key().as_bytes(),
        )
        .is_err());
    }

    #[test]
    fn many_generations_roundtrip() {
        let signing = fixture_signing_key();
        for gen in 0u64..100 {
            let plaintext = format!("msg-{gen}").into_bytes();
            let fields = encrypt_message(
                &plaintext,
                &fixture_channel_key(),
                &fixture_channel_id(),
                &fixture_channel_key_id(),
                gen,
                &signing.to_bytes(),
            )
            .expect("encrypt");
            let decoded = decrypt_message(
                &fields,
                &fixture_channel_key(),
                &fixture_channel_id(),
                signing.verifying_key().as_bytes(),
            )
            .expect("decrypt");
            assert_eq!(decoded.plaintext, plaintext);
            assert_eq!(decoded.generation, gen);
        }
    }

    #[test]
    fn fields_contain_canonical_lengths() {
        let signing = fixture_signing_key();
        let fields = encrypt_message(
            b"x",
            &fixture_channel_key(),
            &fixture_channel_id(),
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");
        assert_eq!(fields.nonce.len(), AES_GCM_NONCE_BYTES);
        assert_eq!(fields.sender_signature.len(), ED25519_SIGNATURE_BYTES);
        assert_eq!(fields.channel_key_id.len(), CHANNEL_KEY_ID_BYTES);
        assert_eq!(fields.ciphertext.len(), 1 + AES_GCM_TAG_BYTES);
    }

    #[test]
    fn wrap_blob_has_canonical_layout() {
        let (_, public, _, kyber_public) = fixture_device_hybrid();
        let blob =
            wrap_key_for_device(&fixture_channel_key(), &public, &kyber_public).expect("wrap");
        assert_eq!(blob.len(), CHANNEL_KEY_BLOB_BYTES);
        // First 32 bytes must be a valid X25519 public key (use it round-trip).
        let mut ephemeral = [0u8; X25519_PUBLIC_KEY_BYTES];
        ephemeral.copy_from_slice(&blob[..X25519_PUBLIC_KEY_BYTES]);
        let _ = X25519Public::from(ephemeral);
        // Bytes 32..1120 are ML-KEM ciphertext, then nonce, then ciphertext+tag.
        assert_eq!(
            blob.len() - (X25519_PUBLIC_KEY_BYTES + KYBER_CIPHERTEXT_BYTES + AES_GCM_NONCE_BYTES),
            AES_KEY_BYTES + AES_GCM_TAG_BYTES
        );
    }

    #[test]
    fn cross_device_unwrap_isolation() {
        // Wrapping for device A must not unwrap with device B's secret, even if both
        // were generated independently.
        let (secret_a, public_a, kyber_secret_a, kyber_public_a) = fixture_device_hybrid();
        let (secret_b, _public_b, kyber_secret_b, _kyber_public_b) = fixture_device_hybrid();
        let channel_key = fixture_channel_key();
        let blob =
            wrap_key_for_device(&channel_key, &public_a, &kyber_public_a).expect("wrap for A");
        let unwrap_a = unwrap_key_blob(&blob, &secret_a, &kyber_secret_a).expect("unwrap with A");
        assert_eq!(*unwrap_a, channel_key);
        assert!(
            unwrap_key_blob(&blob, &secret_b, &kyber_secret_b).is_err(),
            "B must not be able to unwrap A's blob"
        );
    }

    #[test]
    fn signature_binds_to_channel_id_not_just_ciphertext() {
        // Replay-cross-channel attack: a valid envelope from channel X must not
        // verify on channel Y even if all bytes are copied verbatim.
        let signing = fixture_signing_key();
        let channel_x = [0xA1; CHANNEL_ID_BYTES];
        let channel_y = [0xA2; CHANNEL_ID_BYTES];
        let fields = encrypt_message(
            b"crosschan",
            &fixture_channel_key(),
            &channel_x,
            &fixture_channel_key_id(),
            0,
            &signing.to_bytes(),
        )
        .expect("encrypt");

        let on_x = decrypt_message(
            &fields,
            &fixture_channel_key(),
            &channel_x,
            signing.verifying_key().as_bytes(),
        );
        assert!(on_x.is_ok(), "valid on origin channel");

        let on_y = decrypt_message(
            &fields,
            &fixture_channel_key(),
            &channel_y,
            signing.verifying_key().as_bytes(),
        );
        assert!(on_y.is_err(), "must not verify on different channel");
    }
}
